// Code generated by controller-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/netbirdio/kubernetes-operator/api/v1alpha1"
	apiv1alpha1 "github.com/netbirdio/kubernetes-operator/pkg/applyconfigurations/api/v1alpha1"
	internal "github.com/netbirdio/kubernetes-operator/pkg/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=netbird.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("DeploymentOverride"):
		return &apiv1alpha1.DeploymentOverrideApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Group"):
		return &apiv1alpha1.GroupApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupSpec"):
		return &apiv1alpha1.GroupSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupStatus"):
		return &apiv1alpha1.GroupStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResource"):
		return &apiv1alpha1.NetworkResourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceSpec"):
		return &apiv1alpha1.NetworkResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceStatus"):
		return &apiv1alpha1.NetworkResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceReference"):
		return &apiv1alpha1.ResourceReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoutingPeer"):
		return &apiv1alpha1.RoutingPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoutingPeerSpec"):
		return &apiv1alpha1.RoutingPeerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RoutingPeerStatus"):
		return &apiv1alpha1.RoutingPeerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKey"):
		return &apiv1alpha1.SetupKeyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKeySpec"):
		return &apiv1alpha1.SetupKeySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKeyStatus"):
		return &apiv1alpha1.SetupKeyStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
