// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkResourceSpecApplyConfiguration represents a declarative configuration of the NetworkResourceSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// NetworkResourceSpec defines the desired state of NetworkResource
type NetworkResourceSpecApplyConfiguration struct {
	// foo is an example field of NetworkResource. Edit networkresource_types.go to remove/update
	Foo *string `json:"foo,omitempty"`
}

// NetworkResourceSpecApplyConfiguration constructs a declarative configuration of the NetworkResourceSpec type for use with
// apply.
func NetworkResourceSpec() *NetworkResourceSpecApplyConfiguration {
	return &NetworkResourceSpecApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithFoo(value string) *NetworkResourceSpecApplyConfiguration {
	b.Foo = &value
	return b
}
